# Generated by Django 2.2.3 on 2019-07-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casino', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='amount_lost',
            field=models.FloatField(default=0.0, help_text='Amount of real money lost on spins.'),
        ),
    ]
