# Generated by Django 2.2.3 on 2019-07-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casino', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='depleted',
            field=models.BooleanField(default=False),
        ),
    ]
