# Generated by Django 2.2.3 on 2019-07-26 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casino', '0002_wallet_depleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='depleted',
            new_name='is_bonus_depleted',
        ),
    ]
