# Generated by Django 2.2.3 on 2019-07-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casino', '0003_auto_20190726_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='bonus_money',
            field=models.FloatField(default=100.0, help_text='Customer bonus amount given by log ins and deposit'),
        ),
    ]
