# Generated by Django 2.2.3 on 2019-07-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casino', '0004_auto_20190726_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='casino_bonus_deposit',
            field=models.FloatField(default=20.0, help_text='Amount granted if customer deposits larger than 100 euros'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='casino_bonus_login',
            field=models.FloatField(default=100.0, help_text='Customer bonus amount given by log ins and deposit'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='bonus_money',
            field=models.FloatField(default=100.0, help_text='Customer bonus amount'),
        ),
    ]
