# Generated by Django 2.2.3 on 2019-07-28 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casino', '0005_auto_20190726_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='deposit_bonus_amount',
            field=models.FloatField(default=100.0, help_text='Amount of deposit to verify against. If customer deposits an amount larger than this field, we grant him a bonus of the field casino_bonus_deposit'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='casino_bonus_login',
            field=models.FloatField(default=100.0, help_text='Customer bonus amount given by log ins'),
        ),
    ]
