version: "3.7"

services:
  app:
    build: .
    environment:
    - DATABASE_NAME=casino
    - DATABASE_PORT=3306
    - DATABASE_USER=root
    - DATABASE_PASSWORD=0119
    - DATABASE_HOST=db
    networks:
      - backend
    ports:
      - "8000:80"
    depends_on:
      - db

  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
    - MYSQL_DATABASE=casino
    - MYSQL_ROOT_PASSWORD=0119
    networks:
      - backend
    volumes:
      - database:/casino_db

networks:
  backend:
    driver: overlay

volumes:
  database:
